name: ensembleflex
channels:
  - conda-forge
  - bioconda
dependencies:
  # Python dependencies
  - python=3.11
  # -for script functionality
  - glob2=0.7
  - scipy=1.13.1 # version 1.14 is incompatible with ProDy 2.4.
  - prody=2.4.0
  - biopython=1.83
  - matplotlib=3.8.4
  # -for streamlit GUI
  - streamlit=1.36.0
  - pathlib=1.0.1
  - unidecode=1.3.8 # for stoc.py
  - pip=24.0
  - pip:
    - py3Dmol==2.0.0.post2 # only via pip
    - stmol==0.0.9 # only via pip
    - ipython-genutils==0.2.0
  # R dependencies (for script functionality)
  - r-base=4.3.3   #- r-essentials
  - r-biocmanager=1.30.23
  - r-bio3d=2.4_4
  - r-optparse=1.7.5
  - r-r.utils=2.12.3
  - r-pheatmap=1.0.12
  - r-ggplot2=3.5.1
  - r-umap=0.2.10.0
  - r-cluster=2.1.6
  - r-clvalid=0.7
  - r-dplyr=1.1.4
  - r-remotes=2.5.0 # for direct installation from bitbucket
  - bioconductor-msa=1.34.0

