
import glob
import os


def generate_report(str_input_path, output_path):

    os.chdir(output_path) # change working directory to output_path

    # 1. Set up multiple variables to store the titles, text within the report
    page_title_text = 'ProDy Analysis Report'
    title_text = 'ProDy Analysis Report'
    text_intro = '...'
    # list of pdb files
    pdbfiles = glob.glob(str_input_path+"/*.pdb")
    #pdbfiles = args.pdbfiles
    text_rmsd = '...'
    text_pca = '...'
    text_anm_nma = '...'

    # 2. Combine them together using a long f-string
    html = f'''
        <html>
            <head>
                <title>{page_title_text}</title>
            </head>
            <body>
                <h1>{title_text}</h1>
                <p>The following {len(pdbfiles)} files were included in the analysis:</p>
                <div style="height:200px;width:700px;border:1px solid #ccc;font:16px/26px Georgia, Garamond, Serif;overflow:auto;">
                {pdbfiles}
                </div>
                <p>Structure {pdbfiles[0]} served as reference structure.</p>
                <p>Besides root mean square fluctuations (RMSFs) Principal component analysis (PCA) and normal mode analysis (NMA) have emerged as two invaluable tools \
                for studying conformational changes in proteins.</p>
    
                <h2> 1. Root Mean Square Fluctuation (RMSF) Analysis </h2>
                <p>Root mean square fluctuation (RMSF) is a numerical measurement similar to Root mean square deviation \
                (RMSD), but instead of indicating positional differences between entire structures over time, RMSF is a \
                calculation of individual residue flexibility, or how much a particular residue moves (fluctuates) within \
                an ensemble of structures. <br>
                RMSFs shown in the plot are calculated on the C&#945; atoms per residue.</p>
                <img src='RMSF.png' width="700">
                <p>RMSF values are saved in B-factor column of RMSFonReference.pdb for visualisation. \
                Just open the structure in a molecular visualisation program and color by b-factor.</p>
                            
                <h2> 2. Principal Component Analysis (PCA) </h2>
                <p>Principal component analysis (PCA) is a mathematical technique, used to find patterns in high-dimensional \
                datasets, such as protein structures. It enables us to find relationships/patterns, which would be invisible \
                from a pure visual examination. It can be applied to ensembles of protein structures to detect the global, \
                correlated motions of the system (the principal components). PCA is a method that identifies the components \
                which account for the greatest amount of variability in the ensemble.</p>
                <img src='Fluctuations_PCA.png' width="700">
                
                <p>Explained variance in PCA is a statistical measure of how much variation in a dataset can be \
                attributed to each of the principal components (eigenvectors) generated by the PCA. To compute the \
                percentage of variance (information) accounted for by each principal component, the eigenvalue of each \
                component is divided by the sum of eigenvalues.</p>
                <div><object data="PCA_variance.txt"></object></div>
                
                <p>Collectivity of principal components describes the extent to which a mode collectively recruits \
                large portions of the structure. The used function implements collectivity as defined in equation 5 of \
                <a href="https://aip.scitation.org/doi/10.1063/1.469213">[BR95]</a> \
                (<a href="http://prody.csb.pitt.edu/_modules/prody/dynamics/analysis.html#calcCollectivity">source code</a>).</p>
                <div><object data="PCA_mode_collectivity.txt"></object></div>
                
                <img src='Projection_PC1_2.png' width="700">
    
                <h2> 3. Anisotropic Network Model (ANM) Normal Mode Analysis (NMA) </h2>
                <p>Normal Mode Analysis (NMA) is an alternative method to study dynamics of molecules, and does not require \
                an ensemble of structures, but is calculated on a single structure instead. It is based on the theory of \
                vibration and conformational fluctuation is given by a superposition of normal modes. <br>
                The Anisotropic Network Model (ANM) is a simple yet powerful tool made for Normal Mode Analysis of proteins, \
                which has been successfully applied for exploring the relation between function and dynamics for many proteins. \
                It is essentially an Elastic Network Model for the C&#945; atoms with a step function for the dependence of the \
                force constants on the inter-particle distance. <br>
                It represents the biological macromolecule as an elastic mass-and-spring network, to explain the internal \
                motions of a protein subject to a harmonic potential. In the network each node is the C&#945; atom of the residue \
                and the springs represent the interactions between the nodes. The overall potential is the sum of harmonic \
                potentials between interacting nodes. To describe the internal motions of the spring connecting the two atoms, \
                there is only one degree of freedom. Qualitatively, this corresponds to the compression and expansion of \
                the spring in a direction given by the locations of the two atoms. In other words, ANM is an extension of \
                the Gaussian Network Model to three coordinates per atom, thus accounting for directionality. \
                (source: <a href="https://en.wikipedia.org/wiki/Anisotropic_Network_Model">Wikipedia</a>) \
                An ANM instance was generated for the reference structure that stores Hessian matrix (and also Kirchhoff matrix) \
                and subsequently NMA was performed on it, describing the intrinsic dynamics of the protein structure.</p>
                <img src='Fluctuations_ANM.png' width="700">
                <div><object data="ANM_mode_variance.txt"></object></div>
                <div><object data="ANM_mode_collectivity.txt"></object></div>
    
            </body>
        </html>
        '''
    # 3. Write the html string as an HTML file
    with open('analysis_prody_html_report.html', 'w') as f:
        f.write(html)

    # # 4. Convert the HTML file to PDF (problem: embedded text parts are missing)
    # from weasyprint import HTML, CSS
    # css = CSS(string='''
    #     @page {size: A4; margin: 1cm;}
    #     th, td {border: 1px solid black;}
    #     ''')
    # HTML('analysis_prody_html_report.html').write_pdf('analysis_prody_pdf_report.pdf', stylesheets=[css])

    # # option 2 (problem: ContentNotFoundError)
    # import pdfkit
    # options = {"enable-local-file-access": ""}
    # pdfkit.from_file('analysis_prody_html_report.html', 'analysis_prody_pdf_report2.pdf', options=options)
    # pdfkit.from_string(html, 'analysis_prody_pdf_report3.pdf', options=options)
