[browser]

# Internet address where users should point their browsers in order to
# connect to the app. Can be IP address or DNS name and path.

# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser

# Default: "localhost"
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.

# Default: true
gatherUsageStats = true

# Port where users should point their browsers in order to connect to the
# app.

# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser

# Default: whatever value is set in server.port.
serverPort = 8501


# this is needed for local development with docker
[server]
# if you don't want to start the default browser:
headless = true
# you will need this for local development:
runOnSave = true
# you will need this if running docker on windows host:
fileWatcherType = "poll"


[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
#base="light"

# Primary accent color for interactive elements.
#primaryColor="#4fd4b6"

# Background color for the main content area.
# backgroundColor =

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor =

# Color used for almost all text.
# textColor =

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font =

primaryColor="#f63366"
backgroundColor="#ffffff"
secondaryBackgroundColor="#c7dcd7"
textColor="#006b54"
font="sans serif"